name: DevOps Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      first-name:
        description: "First Name"
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello"
      - run: lsb_release -a
      - run: echo "Commit SHA: ${{ github.sha }}"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/checkout@v3
      - run: ls -l
      - run: cat 1.txt
      - run: cat 2.txt
      - run: ./test.sh

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: First name from env
        env:
          FIRST_NAME: ${{ github.event.inputs.first-name }}
        run: echo "First Name: $FIRST_NAME"

      - name: Last name local variable
        run: |
          LAST_NAME="Smith"
          echo "Last Name: $LAST_NAME"

      - name: Phone from secret
        run: echo "Phone: ${{ secrets.PHONE_NUMBER }}"
